import {build} from 'esbuild';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const bundled=await build({stdin:{contents:"import {XRDevice,metaQuest3} from 'iwer';const d=new XRDevice(metaQuest3,{stereoEnabled:true});d.installRuntime({forceInstall:true});d.position.set(1.1,1.7,.7);d.quaternion.set(0,Math.sin(.3),0,Math.cos(.3));d.controllers.left.position.set(-.25,1.35,-.5);d.controllers.right.position.set(.25,1.35,-.25);globalThis.xrTestDevice=d;",resolveDir:process.cwd()},bundle:true,write:false,format:'iife'});
const browser=await chromium.launch({headless:false,args:['--use-angle=metal','--ignore-gpu-blocklist']});const page=await browser.newPage({viewport:{width:1280,height:800}});const errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.addInitScript({content:bundled.outputFiles[0].text});await page.goto(process.env.TEST_URL||'http://localhost:4174',{waitUntil:'networkidle'});assert(await page.evaluate(()=>!document.getElementById('guide').getContext('2d').getImageData(0,0,768,256).data.some(v=>v)),'Menu has no tutorial');await page.locator('#intro[data-ready="1"]').click();await page.waitForTimeout(1000);
assert(await page.evaluate(()=>torde.renderer.xr.isPresenting),'XR session started');assert(await page.evaluate(()=>{const panel=torde.camera.children.find(c=>c.material?.map?.image===document.getElementById('guide'));return panel.position.y>-.23&&torde.state().panelOpen>.98;}),'XR tutorial rises into a readable popup');
assert(await page.evaluate(()=>!torde.state().hasBow&&!torde.bow.visible&&!torde.nocked.visible&&torde.state().tutorial===0),'Start unarmed with movement lesson');
const spawn=await page.evaluate(()=>{const c=torde.renderer.xr.getCamera().cameras;return new T.Vector3().setFromMatrixPosition(c[0].matrixWorld).add(new T.Vector3().setFromMatrixPosition(c[1].matrixWorld)).multiplyScalar(.5).toArray();});assert(Math.abs(spawn[0]-Math.sin(28*.075)*1.8)<.01&&Math.abs(spawn[2]-28)<.01,'Tracked head recentered on path despite physical room offset');assert(await page.evaluate(()=>torde.renderer.xr.getCamera().getWorldDirection(new T.Vector3()).z<-.999),'Spawn faces down the path despite physical head yaw');await page.evaluate(()=>{xrTestDevice.position.set(0,1.7,0);xrTestDevice.quaternion.set(0,0,0,1);torde.rig.rotation.y=0;});
await page.evaluate(()=>xrTestDevice.controllers.right.updateButtonValue('trigger',1));await page.waitForTimeout(100);await page.evaluate(()=>xrTestDevice.controllers.right.updateButtonValue('trigger',0));assert(await page.evaluate(()=>torde.arrows.length===0),'Unarmed trigger cannot fire');
await page.evaluate(()=>torde.place(0,18));await page.waitForTimeout(1200);
await page.evaluate(()=>xrTestDevice.controllers.right.updateButtonValue('trigger',1));await page.waitForTimeout(100);await page.evaluate(()=>xrTestDevice.controllers.right.updateButtonValue('trigger',0));assert(await page.evaluate(()=>torde.state().speech>12),'Early trigger cannot skip sage text');
await page.waitForFunction(()=>torde.state().speech<10.8);await page.evaluate(()=>xrTestDevice.controllers.right.updateButtonValue('trigger',1));await page.waitForTimeout(100);await page.evaluate(()=>xrTestDevice.controllers.right.updateButtonValue('trigger',0));assert(await page.evaluate(()=>torde.state().speech<=6&&torde.state().speech>5&&!torde.state().hasBow),'Right trigger advances fully displayed first phrase');
await page.waitForFunction(()=>torde.state().speech<2.8);await page.evaluate(()=>xrTestDevice.controllers.left.updateButtonValue('trigger',1));await page.waitForTimeout(100);await page.evaluate(()=>xrTestDevice.controllers.left.updateButtonValue('trigger',0));await page.waitForTimeout(600);

assert(await page.evaluate(()=>torde.state().hasBow&&torde.bow.visible&&torde.state().phase===1&&torde.state().tutorial===-1),'Sage gives bow directly after dialogue, without pickup or extra tutorial');assert(await page.evaluate(()=>torde.panel.position.y<-.52&&torde.state().panelOpen<.08),'After dialogue popup folds down to status strip');
await page.evaluate(()=>{torde.place(0,23);xrTestDevice.controllers.left.position.set(-.25,1.35,-.5);});await page.waitForTimeout(150);
const freeArrow=await page.evaluate(()=>{const r=torde.grips.find(g=>g.userData.hand==='right');return torde.nocked.getWorldPosition(new T.Vector3()).distanceTo(r.getWorldPosition(new T.Vector3()));});assert(Math.abs(freeArrow-.42)<.03,'Arrow independently follows right hand');
// Clicking with separated hands must neither pinch the string nor create a shot.
await page.evaluate(()=>xrTestDevice.controllers.right.updateButtonValue('trigger',1));await page.waitForTimeout(120);
assert(await page.evaluate(()=>!torde.state().drawing&&torde.state().draw===0),'Distant hands cannot nock');
assert(await page.evaluate(()=>{const a=torde.bow.userData.string.geometry.attributes.position;return new T.Vector3().fromBufferAttribute(a,1).distanceTo(new T.Vector3().fromBufferAttribute(a,0).lerp(new T.Vector3().fromBufferAttribute(a,2),.5))<.00001;}),'Idle string is exactly straight');
await page.evaluate(()=>xrTestDevice.controllers.right.updateButtonValue('trigger',0));await page.waitForTimeout(100);assert(await page.evaluate(()=>torde.state().lastShot===-10),'Distant click does not fire');
// Hold trigger, bring the nock close, then pull: distance alone is not tension.
await page.evaluate(()=>{xrTestDevice.controllers.right.position.set(-.25,1.35,-.38);xrTestDevice.controllers.right.updateButtonValue('trigger',1);});await page.waitForTimeout(150);
assert(await page.evaluate(()=>torde.state().drawing&&torde.state().draw<.01),'Close hands nock with no initial tension');
await page.evaluate(()=>{globalThis.pulses=[];const a=torde.controllers.find(c=>c.userData.source?.handedness==='right').userData.source.gamepad.hapticActuators[0];a.pulse=(...args)=>{pulses.push(args);return Promise.resolve(true);};});await page.waitForTimeout(200);
await page.evaluate(()=>{xrTestDevice.controllers.right.position.set(-.2,1.65,.25);xrTestDevice.controllers.left.quaternion.set(.70710678,0,0,.70710678);});await page.waitForTimeout(300);
const draw=await page.evaluate(()=>torde.state().draw);assert(draw>.5,`Two-handed bow pull: ${draw}`);
const alignment=await page.evaluate(()=>{const l=torde.grips.find(g=>g.userData.hand==='left').getWorldPosition(new T.Vector3()),r=torde.grips.find(g=>g.userData.hand==='right').getWorldPosition(new T.Vector3());const axis=l.sub(r).normalize(),bowAxis=new T.Vector3(0,0,-1).applyQuaternion(torde.bow.getWorldQuaternion(new T.Quaternion()));const string=torde.bow.userData.string.geometry.attributes.position,mid=new T.Vector3().fromBufferAttribute(string,1);torde.bow.localToWorld(mid);return {dot:axis.dot(bowAxis),stringError:mid.distanceTo(r),pulses};});const gripAlignment=await page.evaluate(()=>{const l=torde.grips.find(g=>g.userData.hand==='left');return {axis:new T.Vector3(0,1,0).applyQuaternion(torde.bow.getWorldQuaternion(new T.Quaternion())).dot(new T.Vector3(0,0,-1).applyQuaternion(l.getWorldQuaternion(new T.Quaternion()))),center:torde.bow.getWorldPosition(new T.Vector3()).distanceTo(l.getWorldPosition(new T.Vector3())),arrowAxis:new T.Vector3(0,0,-1).applyQuaternion(torde.nocked.getWorldQuaternion(new T.Quaternion())).dot(l.getWorldPosition(new T.Vector3()).sub(torde.grips.find(g=>g.userData.hand==='right').getWorldPosition(new T.Vector3())).normalize())};});assert(gripAlignment.axis>.999,'Bow handle stays along left grip axis during drawing');assert(gripAlignment.center<.001,'Handle stays centered in palm');assert(gripAlignment.arrowAxis>.999,'Arrow follows two-hand aim');assert(alignment.stringError<.002,'String center follows drawing hand');assert(alignment.pulses.length===1,'Single haptic at full draw');
await page.evaluate(()=>xrTestDevice.controllers.right.updateButtonValue('trigger',0));await page.waitForTimeout(100);assert(await page.evaluate(()=>torde.state().lastShot>0),'XR arrow release');
assert(await page.evaluate(()=>{const a=torde.bow.userData.string.geometry.attributes.position;return Math.abs(a.getX(1))+Math.abs(a.getY(1))+Math.abs(a.getZ(1)-.1)<.00001;}),'Release resets every coordinate of string midpoint');
const releasedShot=await page.evaluate(()=>torde.state().lastShot);
for(let i=0;i<3;i++){await page.evaluate(()=>xrTestDevice.controllers.right.updateButtonValue('trigger',1));await page.waitForTimeout(100);await page.evaluate(()=>xrTestDevice.controllers.right.updateButtonValue('trigger',0));await page.waitForTimeout(100);}
assert.equal(await page.evaluate(()=>torde.state().lastShot),releasedShot,'Repeated distant trigger clicks cannot machine-gun arrows');
const walkBefore=await page.evaluate(()=>torde.rig.position.z);await page.evaluate(()=>xrTestDevice.controllers.left.updateAxes('thumbstick',0,-1));await page.waitForTimeout(600);await page.evaluate(()=>xrTestDevice.controllers.left.updateAxes('thumbstick',0,0));const walkAfter=await page.evaluate(()=>torde.rig.position.z);assert(walkAfter<walkBefore-1,'Left stick walks continuously');const before=await page.evaluate(()=>torde.rig.position.z);
await page.evaluate(()=>xrTestDevice.controllers.right.updateAxes('thumbstick',0,-1));const ranges=[];for(const angle of [-.5,0,.5]){await page.evaluate(a=>xrTestDevice.controllers.right.quaternion.set(Math.sin(a/2),0,0,Math.cos(a/2)),angle);await page.waitForTimeout(150);ranges.push(await page.evaluate(()=>Math.hypot(torde.teleRing.position.x-torde.rig.position.x,torde.teleRing.position.z-torde.rig.position.z)));}assert(ranges[0]<ranges[1]&&ranges[1]<ranges[2],'Magic walk: lower is closer, higher is farther');await page.evaluate(()=>xrTestDevice.controllers.right.quaternion.set(0,0,0,1));await page.waitForTimeout(150);await page.evaluate(()=>xrTestDevice.controllers.right.updateAxes('thumbstick',0,0));await page.waitForTimeout(200);
const after=await page.evaluate(()=>torde.rig.position.z);assert(after<before-.5,`Teleport ${before} -> ${after}`);assert.equal(await page.evaluate(()=>torde.state().taught&7),7,'Movement, teleport and shooting lessons complete through real input');
// Actual controller movement, swept arrow-tip collision, and withdrawal to re-arm.
await page.evaluate(()=>{torde.clear();torde.place(0,23);xrTestDevice.controllers.right.quaternion.set(0,0,0,1);xrTestDevice.controllers.right.position.set(.25,.65,-.1);});await page.waitForTimeout(150);
// Quest target-ray and grip poses have different axes: point the actual arrow horizontally.
await page.evaluate(()=>{const q=torde.grips.find(g=>g.userData.hand==='right').quaternion.clone().invert();xrTestDevice.controllers.right.quaternion.set(q.x,q.y,q.z,q.w);});await page.waitForTimeout(150);
await page.evaluate(()=>{globalThis.stabWolf=torde.spawn(.25,21.45);stabWolf.hp=2;stabWolf.speed=0;stabWolf.attack=999;});await page.waitForTimeout(200);assert(await page.evaluate(()=>stabWolf.hp===2),'Stationary arrow contact does no damage');
for(const z of [-.13,-.16,-.19,-.22]){await page.evaluate(z=>xrTestDevice.controllers.right.position.z=z,z);await page.waitForTimeout(20);}
assert(await page.evaluate(()=>stabWolf.hp===1),'Forward hand thrust stabs once');
await page.waitForTimeout(200);for(const z of [-.25,-.28,-.31]){await page.evaluate(z=>xrTestDevice.controllers.right.position.z=z,z);await page.waitForTimeout(20);}
assert(await page.evaluate(()=>stabWolf.hp===1),'Continuing same thrust cannot deal repeated damage');
await page.evaluate(()=>xrTestDevice.controllers.right.position.z=-.1);await page.waitForTimeout(80);
for(const z of [-.13,-.16,-.19]){await page.evaluate(z=>xrTestDevice.controllers.right.position.z=z,z);await page.waitForTimeout(20);}
assert(await page.evaluate(()=>stabWolf.dead>0),'Withdraw then stab again defeats strong wolf');
await page.screenshot({path:'.js13k-check/xr-stereo.png'});
// Spawn during the actual XR update, when Three's render camera is not yet in world space.
// Exercise room-scale translation, recenter/snap yaw and head yaw together.
const wolfHeadings=[];
for(const [rigYaw,headYaw]of [[Math.PI,0],[-1.2,.7],[.4,2.2],[1.1,-1.8]]){
 await page.evaluate(([r,h])=>{torde.clear();torde.set({phase:0,encounters:0});torde.place(0,-16);torde.rig.rotation.y=r;xrTestDevice.position.set(1.1,1.7,.7);xrTestDevice.quaternion.set(0,Math.sin(h/2),0,Math.cos(h/2));},[rigYaw,headYaw]);await page.waitForTimeout(100);await page.evaluate(()=>torde.setPhase(1));await page.waitForTimeout(100);
 const result=await page.evaluate(([r,h])=>{const forward=new T.Vector3(0,0,-1).applyAxisAngle(new T.Vector3(0,1,0),r+h),origin=new T.Vector3(xrTestDevice.position.x,xrTestDevice.position.y,xrTestDevice.position.z).applyQuaternion(torde.rig.quaternion).add(torde.rig.position);return {rigYaw:r,headYaw:h,dots:torde.wolves.map(w=>w.g.position.clone().sub(origin).setY(0).normalize().dot(forward))};},[rigYaw,headYaw]);assert(result.dots.length===2&&result.dots.every(d=>d>.84),'Initial wolves appear in front of current tracked gaze, inside XR frame');wolfHeadings.push(result);
 const before=await page.evaluate(()=>torde.rig.position.toArray());await page.evaluate(()=>xrTestDevice.controllers.left.updateAxes('thumbstick',0,-1));await page.waitForTimeout(200);await page.evaluate(()=>xrTestDevice.controllers.left.updateAxes('thumbstick',0,0));assert(await page.evaluate(([before,yaw])=>torde.rig.position.clone().sub(new T.Vector3(...before)).setY(0).normalize().dot(new T.Vector3(0,0,-1).applyAxisAngle(new T.Vector3(0,1,0),yaw))>.99,[before,rigYaw+headYaw]),'Walking uses same real gaze after rig and head rotation');
}
await page.evaluate(()=>torde.renderer.xr.getSession().end());await page.waitForTimeout(200);assert(!(await page.evaluate(()=>torde.renderer.xr.isPresenting)),'XR session exit');
assert.equal(errors.length,0,errors.join('\n'));const result={emulatedDevice:'Meta Quest 3 / IWER, NOT physical headset',stereo:true,automaticBowGift:true,dialogueAdvance:true,organicPopup:true,wolfHeadings,menuTutorial:false,spawn,notching:true,noDistantRapidFire:true,straightIdleString:true,meleeThrust:true,freeArrowOffset:freeArrow,bowDraw:draw,alignment,gripAlignment,walk:{before:walkBefore,after:walkAfter},arrowRelease:true,teleport:{before,after,ranges},sessionExit:true,errors};
await writeFile('.js13k-check/xr-report.json',JSON.stringify(result,null,2));console.log(result);await browser.close();
